import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
// import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

//   useEffect(()=>{
//     require ('\webpage\node_modules\bootstrap\js')
//   }
// )

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
